sudo: required

language: python

python:
  - "3.5"

before_install:
  - apt-get update

install:
  - apt-get install -y python3-dev
  - apt-get install -y libpq-dev
  - apt-get install -y gettext

before_script:
  - pip3 install -r tbl/requirements.txt
  - python3 tbl/manage.py makemigrations
  - python3 tbl/manage.py migrate
  - django-admin makemessages
  - django-admin compilemessages

script:
  - pytest
