language: python

# Specify the version of python
python:
  - "3.5"

branches:
  only:
    - master
    - dev

# Update the system
before_install:
  - sudo apt-get update

# Install enviroment dependencies
install:
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y libpq-dev
  - sudo apt-get install -y gettext
  - sudo apt-get install -y build-essential

# Install project dependencies
before_script:
  - pip3 install -r tbl/requirements.txt
  - python3 tbl/manage.py makemigrations
  - python3 tbl/manage.py migrate
  - mkdir tbl/locale
  - django-admin makemessages
  - django-admin compilemessages

# Run the tests and create coverage.xml
script:
  - pytest
  - pytest --cov-report xml --cov=.

# Insert a file coverage.xml into codacy to get coverage
after_script:
  - python-codacy-coverage -r coverage.xml
