language: python

python:
  - "3.5"     # 3.5 master branch
  - "3.5-dev" # 3.5 development branch

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y sqlite

install:
  - pip3 install -r tbl/requirements.txt

before_script:
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - pytest --maxfail=1

# deploy:
#   provider: heroku
#   api_key:
#     secure: ""
#   app: tbl
#   run:
#     - python3 manage.py makemigrations
#     - python3 manage.py migrate
