language: python

# Specify the version of python
python:
  - "3.5"

branches:
  only:
    - master
    - dev

# Update the system
before_install:
  - sudo apt-get update

# Install enviroment dependencies
install:
  - sudo apt-get install -y python3-dev
  - sudo apt-get install -y libpq-dev
  - sudo apt-get install -y gettext

# Install project dependencies
before_script:
  - pip3 install -r tbl/requirements.txt
  - python3 tbl/manage.py makemigrations
  - python3 tbl/manage.py migrate
  - django-admin makemessages
  - django-admin compilemessages

# Run the tests
script:
  - pytest
