version: '2'
services:
  tbl:
    # Uses an image that's built from the Dockerfile in the dockers directory
    build: .
    # Name the image and insert a version
    image: tbl_image:2.0
    # Specify a custom container name.
    container_name: tbl
    # Set the secret_key to enviroment
    environment:
      - SECRET_KEY='n=38@=sss#wz02i6j^%edl3-0n^=5l%^d(t=q^a088hi816-f0'
    # Forwards the exposed port 5050 on the host machine to port 5050 on the container.
    ports:
      - '5050:5050'
    # command to execute inside the docker
    command: ['python3', 'tbl/manage.py', 'runserver', '0.0.0.0:5050']
