version: '2'
services:

  tbl:
    # Uses an image that's built from the Dockerfile in the current directory
    build: .
    # Mounts the project directory on the host to /tbl inside the container, allowing you
    # to modify the code without having to rebuild the image
    volumes:
      - .:/tbl
    # Forwards the exposed port 8080 on the container to port 8080 on the host machine.
    ports:
      - '8080:8080'
