engines:
  # Engine which reports issues when it finds similar code blocks
  # identical code (same variable names and structure)
  # and similar code (copy and paste)
  duplication:
    enabled: true
    config:
      languages:
        # Minimum mass a code block have to be analyzed for duplication
        count_threshold: 3
        python:
          python_version: 3
          # Refers to the size of the duplicated code
          mass_threshold: 60

  # Radon provides Cyclomatic Complexity checks on Python code.
  radon:
    enabled: true
    config:
      # The threshold represents the lower bound of complexity scores reported.
      threshold: "B"

  # Search for the TODO, FIXME, ... string in yout project
    fixme:
      enable: true
      config:
        strings:
          - FIXME
          - TODO
          - BUG

  # Is a python stylesheet analyzis
  pep8:
    enabled: true

# Sets the type of file to be analyzed
ratings:
  paths:
    - "**.py"

# Exclude some files to be analyzed
exclude_paths:
    - "manage.py"
    - "**/migrations/**.py"
    - "**/__init__.py"
